SplusEins/SplusEins

webpack.config.js
Compiliert das backend-Typescript in eine einzelne Datei nach `dist/server/server.js` für das Deployment auf spluseins.de
=> webpack: Add server binary output

components/dayspan-custom-calendar.vue, pages/index.vue
Der Kalender war größer als der äußere Container, weswegen man zwei Scrollbalken hatte.
Noch offen: Das Padding unter der Datumsleiste und zwischen Kalender und Footer stimmt noch nicht.
=> Fix calendar scrolling inside container

components/spluseins-about.vue, components/spluseins-calendar.vue
Änderungen
* Explizit "inoffiziell" in den About-Dialog geschrieben
* Im Footer splus mit Link als Datenquelle eingetragen. Auf sm war nicht genug Platz, dort wird das Jahr und der Name ausgeblendet.
=> Footer: Add more disclaimers

components/custom-timetable-dialog.vue, components/custom-timetables-list.vue, store/splus.js
Ich habe ein Modal geschrieben, in dem man einen Titel eingeben kann und aus einer Liste von Kursen auswählen kann. Die Liste von Kursen kann man durchsuchen. Das Modal lässt sich über den drawer öffnen. Auf mobilen Geräten ist der Dialog im Vollbildmodus.
Die Kursliste ist nur ein Platzhalter, die muss serverseitig generiert werden. Den eigenen Plan zu speichern geht aus gleichem Grund auch noch nicht. Das möchte ich in einem separaten PR machen um möglichst kleinschrittig zu arbeiten.
Edit: Wollen wir "schedule" oder "timetable" als Terminologie verwenden? timetable ist britisch, schedule amerikanisch.
=> Custom schedule

components/spluseins-calendar.vue, pages/index.vue
Für Netlify wird das HTML in einem statischen build einmalig gerendert. Zu dem Zeitpunkt des renderns werden die Daten für die aktuelle Woche aus der API geladen. Der Client ruft die Daten nicht noch einmal ab.
Die Folge: Ist der build eine Woche her, ist der Plan leer.
Mit diesem PR wird eine Ausnahme für den statischen build hinzugefügt und im Client werden die Daten abgerufen, wenn sie noch nicht vorhanden sind.
=> Fix no lectures on page load after static build

components/spluseins-snackbar.vue, pages/index.vue, store/splus.js
Eine Snackbar (auch genannt Toast) informiert nun den Nutzer, wenn es bei der Verbindung zur spluseins-API Probleme gab.
=> Add error handling to UI

components/spluseins-calendar.vue, pages/index.vue
- der Unterschied kam zustande, da die Scrollbar auf mobilen Geräten dünner ist als auf Fullsize Geräten
- lieber "px" als "em" benutzen weil sich "em" weitervererbet, das heißt "2em" sind dann in der nächsten Vererbungsstufe mit "2em" schon "4em"
**Tested on Laptop, Smartphone and Ipad**
=> Adjusted splus disclaimer position

components/__tests__/spluseins-cookie-snackbar.spec.ts, components/__tests__/spluseins-error-snackbar.spec.ts, components/spluseins-cookie-snackbar.vue, components/spluseins-error-snackbar.vue, nuxt.config.js, package-lock.json, package.json, pages/index.vue, plugins/vuex-persist.js, store/privacy.js
Änderungen:
* Eine Teilmenge von store-Daten werden mit vuex-persist im LocalStorage des Browsers gespeichert.
* DSGVO-verträglich wird vorher in einer Snackbar nach Zustimmung dafür gefragt.
Zum Testen könnt ihr `localStorage.clear()` in der Web-Konsole ausführen oder "Cookies und Browserdaten löschen" im Menü auswählen.
Für die Zukunft: Man kann den gesamten Storage damit abspeichern, das schließt die lectures aus der API ein. Damit hat man offline-Unterstützung! Wenn man das jetzt aber schon aktiviert, werden die Daten nie neu geladen und könnten out of date sein, das kommt also am besten in eine separate Story.
Wenn #45 gemerged ist, müssen die darin neu eingeführten store-Attribute auch selektiert werden.
=> Persist store state if permitted

concourse/credentials.yml.example, concourse/pipeline.yml
In Telegram wird nun über erfolgreiche, fehlgeschlagene und abgebrochene Builds benachrichtigt.
Credentials stehen in Tello.
=> Concourse Telegram Notifications

components/custom-timetable-dialog.vue, components/custom-timetables-list.vue, components/general-timetables-list.vue, components/spluseins-calendar.vue, components/spluseins-side-nav.vue, layouts/default.vue, nuxt.config.js, pages/_schedule.vue, pages/index.vue, plugins/vuex-persist.js, store/index.js, store/splus.js
Follow-Up zu / hängt ab von #35
* Der erste Parameter der URL ist die Stundenplan-ID (Nuxt generiert dynamische Routen für Dateien mit Unterstrich, siehe https://nuxtjs.org/guide/routing)
* Beispiel-URL: spluseins.de/SPLUSA2822D
* Beim direkten Aufruf kann der Nuxt-Server die Seite direkt rendern!
* In der Sidebar stehen jetzt Links. Deswegen schließt sie sich nach dem Wechseln des Plans.
* Im Store werden die lectures beim schedule-Wechsel nicht mehr gelöscht, Nuxt leert den sowieso beim Seitenwechsel.
Nicht so cool:
=> Make view state shareable, Add multiple custom schedules

server/model/RichLecture.ts
Tests laufen jetzt auch auf Systemen auf denen UTC nicht die eingestellte Zeitzone ist.
=> Moment timezone UTC

components/course-multiselect.vue, components/custom-timetable-dialog.vue, components/custom-timetables-list.vue, components/timetable-select.vue, store/splus.js
Änderungen:
* Im Dialog kann man mehrere Pläne in die Tabelle laden.
* Das URL-Schema und das Laden eines eigenen Plans ist entsprechend angepasst.
Offene Probleme:
=> Support custom schedules with multiple bases

components/spluseins-calendar.vue, store/splus.js
Änderungen:
* API requests werden nicht erneut geschickt, wenn die Daten im Store existieren. Der empty calendar flash ist damit weg.
* Es wird beim Ansehen des Kalenders im Hintergrund die nächste Woche geladen. Dadurch erhöht sich die perceived performance.
⚡️ ⚡️ ⚡️
=> Deduplicate API requests and prefetch following week

components/custom-timetables-list.vue, components/favorite-timetables-list.vue, components/general-timetables-list.vue, components/install-button-list.vue
Wie von vuetify empfohlen. Damit ist der Abstand zwischen list subheader und divider nicht genau so groß wie zwischen subheader und nächstem Element.
=> Use subheader in lists to fix padding

components/dayspan-custom-calendar.vue, store/splus.js
Der Event-Text wird nun nach dem Titel und nach dem Dozenten umgebrochen.
So entstehen im besten Fall 3 Zeilen, oft aber mehr, da der Text zu lang ist.
Ab 4 Zeilen passt die Beschreibung bei 90 min Vorlesungen nicht mehr vollständig in das Event Fenster.
Ist erstmal eine vorübergehende Lösung.
Eine Idee wäre, dass man nur wichtige Dinge wie den Titel in das Event packt und den Rest über einen kleinen Info-Popup bekannt gibt.
=> Event text wrap

plugins/dayspan.config.js, store/splus.js
Sieht so aus:
Die Erkennung von gleichzeitigen Events funktioniert anhand von den Startzeitpunkten. Wie man sieht, überlappen sich zwei Events, die sich umschließen. Ebenso überlappen sich Events, die kurz hintereinander starten.
Das ist aber nicht trivial zu lösen. Ein Fall: A umschließt B und C, jetzt müssten B und C auf eine Seite kommen und alle drei 50% der Breite haben. Dafür muss man wahrscheinlich eine Art Layoutmanager schreiben…
Wenn man anhand des Starts vergleicht, kann man aber den Titel lesen, deswegen ist das erst einmal gut genug.
=> Display parallel events side by side

process-prod.yml
Pro CPU-Kern wird jeweils ein Prozess für den API & Nuxt server gestartet. pm2 macht automatisches load balancing.
Dokumentation dazu: https://pm2.io/doc/en/runtime/guide/load-balancing/
=> Scale production pm2 services to all cores

store/splus.js
As reported by @BrainConverter, wenn ein personalisierter Kalender mehrere sich überschneidenden Basen hat, wurden die Vorlesungen doppelt angezeigt.
before
after
=> Fix custom schedule duplicating lectures

components/custom-timetable-dialog.vue
Motivation:
Der Dialog für den personalisierten Kalender zeigt nur Vorlesungen der aktuellen Woche an. Manche VL laufen aber zweiwöchentlich oder unregelmäßig und können nicht ausgewählt werden.
Änderung:
Lade diese und die nächsten 3 Wochen. Das Semester geht nur noch 4 Wochen, deswegen reicht das ab morgen. 💩 
Das ist nicht ganz so schlimm, wie es aussieht, weil es nur wenige Kilobytes sind und im Browser und auf dem Server gecached wird.
Für nächstes Semester können wir dann eine bessere Lösung finden 😁
=> Load whole month into custom schedule dialog

components/__tests__/spluseins-cookie-snackbar.spec.ts, components/spluseins-cookie-snackbar.vue, plugins/vue-matomo.js, plugins/vuex-persist.js, store/privacy.js
Änderung: Ersetze den Inhalt der Cookie-Snackbar durch die Optionen "Nichts / Einstellungen / Erlauben". Deaktiviere und lösche Matomo-Cookies für die ersten beiden Optionen. Matomo funktioniert auch ohne Cookies.
Hier ist nochmal die API-Dokumentation für Matomo: https://developer.matomo.org/api-reference/tracking-javascript
Das ist jetzt nach diesem Ratgeber gehalten, der sagt, dass Tracking grundsätzlich okay ist, weil wir die Daten nicht verarbeiten (lassen), sondern nur für uns nutzen: http://www.rechtzweinull.de/archives/2553-ist-tracking-nach-25-mai-2018-nur-noch-mit-einwilligung-bewertung-der-stellungnahme-der-datenschutzbehoerden-zu-tracking-targeting-co.html
=> Ask for consent for Matomo cookies

components/custom-timetables-list.vue, components/general-timetables-list.vue, nuxt.config.js, pages/plan/_schedule.vue, store/splus.js
Ersetze den URL-Parameter für den Namen durch einen Query-Parameter, damit in Matomo der Query gefiltert werden kann.
Bewege alle Seiten nach /plan, um Konflikte mit neuen Seiten zu verhindern.
Macht bestehende Lesezeichen kaputt.
=> Move schedules to /plan, make name a query param

components/favorite-timetables-list.vue, components/general-timetables-list.vue, store/splus.js
In #101 habe ich vergessen, die `scheduleToRoute` der favorites mit anzupassen. Beim Klicken eines Favorits gab es einen Fehler.
Die Funktion habe ich in den store bewegt, weil sie von general timetables und favorite timetables verwendet worden ist.
Langfristig sollten wir solche utility-Funktionen (`scheduleToRoute`, `uniq`, …) aus dem store in eine Bibliothek bewegen, weil sie mit dem store selbst nichts zu tun haben.
=> Fix broken favorites route

components/dayspan-custom-calendar.vue, components/spluseins-calendar.vue
Änderungen:
* "Favorite" auf sehr kleinen Displays (iPhone 5, Galaxy S5) in das Dreipunktemenü verschoben
* Matomo für Bearbeiten & Löschen-Button hinzugefügt (ungetestet)
* Der Bearbeiten-Knopf wird als "Personalisieren" an normalen Plänen angezeigt
=> Add edit button to regular schedules, track buttons, fix xs layout

components/custom-timetable-dialog.vue
Der Custom Timetable Dialog ist in jedem Plan eingebunden. In ihm wurden in mounted() schon alle Pläne der nächsten Wochen vorgeladen. Jetzt wird darauf gewartete, dass der Dialog geöffnet wird und erst dann wird geladen.
=> Fix too many api requests

pages/plan/_schedule.vue
Habe Matomo so konfigueriert, dass der Parameter "name" in der URL nicht auftaucht, jedoch steht der Name des personalisierten Plans noch im Page Header.
=> Remove title of custom plan in page header

assets/ds-de.js, components/dayspan-custom-calendar.vue, components/spluseins-calendar.vue, plugins/dayspan.config.js, store/splus.js
Wenn man auf ein Event clickt wird nun der dayspan event Dialog angezeigt.
In diesem sieht man nun den Raum und die Info, dafür wird im Event selbst nur noch der Titel angezeigt.
TODO für nächste PRs:
- Zeit in den Dialog einbinden, dazu muss inder dayspan.config.js die Methode getEventOccurences überarbeitet werden, also die Verschiebung der Events wieder "herausgerechnet" werden
- Eventtitel umbrechen
=> Basic Event Dialog

assets/schedules.json, server/controllers/splus.ts, server/lib/SplusApi.ts, store/splus.ts
Änderungen:
* Für an die API geschickte IDs wird entschieden, ob sie zu einem setplan gehört.
* Der API-Wrapper schickt den entsprechenden Request.
* Wenn eine ID nicht in der Timetables-JSON existiert, wird 404 zurückgeliefert, statt dass ein request gegen splus geschickt wird.
* `schedule` zu `timetable` umbenannt und `"` durch `'` ersetzt.
=> Add API support for setplan

nuxt.config.js
Ich habe herausgefunden, dass der statische build von dynamisch generierten URLs wegen #101 wieder funktioniert, ohne dass man die routes in der Konfiguration angibt. Vor #101 war das nötig, weil die Netlify-Seiten sonst 404 waren.
Das Entfernen beschleunigt den statischen build und ist hoffentlich ein workaround für die Ressourcenprobleme, die in #137 durch das Hinzufügen von noch mehr Plänen entstanden sind.
=> Nuxt generate: Do not prebuild schedules

components/basic-utilities-list.vue, components/copy-text-dialog.vue, components/custom-timetable-dialog.vue, components/dayspan-custom-calendar.vue, components/install-button-list.vue, components/spluseins-calendar.vue, components/spluseins-header.vue, components/timetable-select.vue, nuxt.config.js, package-lock.json, package.json
Weil `nuxt-material-icons` noch als Modul geladen worden ist, hatten wir zwei Schriftarten (material-icons und mdi) geladen.
* Die Abhängigkeit habe ich entfernt. Das reduziert die Größe der `node_modules` und unserer Seite.
* Icons habe ich entsprechend ihrer mdi counterparts umbenannt.
* Es gab ein "Theme wechseln"-Icon und das habe ich eingesetzt. Sieht das gut aus?
=> Fully replace material-icons by mdi

components/spluseins-calendar.vue
Wenn man im Kalender nach vorne scrollt, landet man bei Woche 1. Man sieht zum Beispiel die Prüfungstermine nicht.
Mit diesem workaround sollte es erst einmal gehen.
=> Calendar: Fix wrong week/year transition

assets/timetables.json
Die ID ist die gleiche wie im Block darüber gewesen (M-BM1b), nuxt gibt bei doppelten Listen-IDs in der `general-timetables-list` eine Warnung oder einen Fehler aus.
=> Timetables Maschinenbau: Fix duplicate

components/dayspan-custom-calendar.vue, plugins/dayspan.config.js
wie in #148 angefragt
hängt von #150 ab
Erhöhe die Höhe der Stunden im Kalender von 40px auf 50px, damit auf 1920x1080 die Seite komplett ausgefüllt wird. Unseren Analytics nach ist das die häufigste höchste Bildschirmhöhe 📈 
Sieht das gut aus?
=> Calendar: Optimize for desktop

components/custom-timetable-dialog.vue
Weil die Vorlesungen, die in der "personalisierter Plan"-Liste angezeigt werden, vom aktuellen Datum + 3 Wochen geladen werden, kann man jetzt, einen Monat vor Beginn des Semesters, noch nichts auswählen.
Um das Problem zu umgehen, habe ich die 5 ersten Wochen des SS19 hartkodiert. 💩
=> Custom timetable: Preload weeks 10 to 14

components/spluseins-calendar.vue, store/splus.ts
Wenn man den Plan wechselt, landet man bei der "heute"-Woche. Das nervt.
Jetzt bleibt man in der gewählten Woche.
=> Preserve week pagination on timetable switch

package-lock.json, package.json
https://www.npmjs.com/package/vue-matomo
Sprung von Version 0.5.1 auf 3.7.0 behebt auch die störenden Konsolenausgaben 👍.
=> Update matomo version

pages/plan/_timetable.vue
Wenn man einen Plan aus der Liste auswählt, hat man keinen "Personalisierten Plan" ausgewählt, aber so steht es im Dokumententitel, das hat mich gestört
=> Timetable: Update title

components/spluseins-calendar.vue, components/upcoming-lectures-card.vue, pages/plan/_timetable.vue, store/splus.ts
In #168 habe ich `resetWeek` entfernt und übersehen, dass damit beim ersten Laden die Daten für die Woche `undefined` abgerufen werden und mit #161 hat sich ein Konflikt ergeben, weil dort `resetWeek` aufgerufen wird.
Jetzt ist es wieder drin, aber besser als vorher:
* Sa/So wird die nächste Woche gewählt und die Logik liegt jetzt im Store statt in dem Kalender
* beim Wechseln des Kalenders gibt es keinen reset
* jetzt geht es bestimmt im statischen build auch
* bis zu Semesterbeginn SS19 ist die erste Woche Standard
=> Set a sensible default week

components/copy-text-dialog.vue, components/general-timetables-list.vue, components/last-changes-card.vue, components/mensa-card.vue, components/spluseins-about.vue, components/upcoming-lectures-card.vue, pages/index.vue
Ein paar Sachen welche mit gestört hatten:
- im About Dialog hat ein padding gefehlt und das GitHub Icon war im DarkTheme schlecht erkennbar
- im Copy-Dialog hat ein padding gefehlt
- die last-changes-card war veraltet
- die Anordnung der Cards im Dashboard hat mir nicht so gut gefallen
- das Icon der upcoming-lectures-card war zu dominant, es ist nun nicht mehr gefüllt sonder hat nur noch ein Outline
=> UI Changes + matomo event fix

components/upcoming-lectures-card.vue, pages/index.vue
Im Master wird heute (Samstag) im Dashboard die Mensa-Card angezeigt, obwohl sie heute nicht geöffenet hat. Nutzt man v-if statts v-show funktioniert es. Das liegt daran, dass die verwendete Direktive d-flex genau wie v-show die CSS-Property "display" verändert und dann v-show überschreibt. 😆 
Könnte man die Reihenfolge der Direktiven ändern, würde es sicher gehen, aber das erlaubt CheckStyle nicht.
=> Fix mensa card display

server/App.ts, server/controllers/mensa.ts, server/controllers/news.ts
Scraped die News-Box der ostfalia.de-Seite und macht die Artikeldaten über `/api/news/ostfalia` in folgendem Format zugänglich:
```json
[{
"title":"Es sind noch Studienplätze frei!",
"link":"https://www.ostfalia.de/cms/de/campus/detail/news/be1e550e-1eea-11e9-99a4-d96edd3be9f9",
"text":"Wer sich beeilt, kann sich jetzt noch für das Sommersemester 2019 bewerben!"
}]
```
@BrainConverter go to town 🙂
=> Add Ostfalia news API endpoint

components/custom-timetable-dialog.vue, components/timetable-select.vue
- Wenn man einen geladenen Schedule gelöscht hat wurden alle selectedCourses statt nur die Kurse des gelöschten Schedules abgewählt.
- Der Button zum Laden eines Planes ist nun deaktiviert, wenn er bereits geladen ist.
- Der Button zum Laden eines Planes ist nun nicht mehr "small".
=> Custom Schedule Dialog Fixes

components/calendar-action-bar.vue, components/responsive-icon-button.vue, server/controllers/ics.ts, server/controllers/news.ts, server/controllers/splus.ts, store/splus.ts
Änderungen:
* Die Button-Zeile vom Kalender getrennt
* Der Titel-Filter ist in der ICS-API jetzt optional, standard ist "alle Vorlesungen"
* Die ICS-API gibt 404 zurück, wenn die übergebenen timetables nicht existieren
* Cache-Header für alle 404s von der API gesetzt
* Button zum Öffnen des ICS in Outlook, der Kalender-App oder anderen Anwendungen hinzugefügt
Bitte mit verschiedenen Geräten und Anwendungen testen 🙂
=> Add link to ICS in calendar action bar

pages/plan/_timetable.vue
Altes Verhalten: https://spluseins.de/plan/DOESNOTEXIST erzeugt einen Fehler 500
Neues Verhalten: http://deploy-preview-216--spluseins.netlify.com/plan/DOESNOTEXIST erzeugt einen Fehler 404
=> Show 404 if plan does not exist

components/stats-card.vue
https://deploy-preview-219--spluseins.netlify.com/plan?id=SPLUS7EEB0A&id=SPLUS087146&id=SPLUS087145&course=BKD&course=BuR&course=CM&course=D&course=MC3S&course=SEASEiK&course=SEAS&course=SSaCEASuS&course=UCK&course=URuA&course=WP&name=Mein%20Stundenplan&v=1
Vom Plugin wurde eine total-Wert der einzelnen Sections von 100.0000000001% errechnet was größer als der default total-Wert von 100% war.
=> Fix sections calculation bug

assets/meta-information.json, nuxt.config.js, pages/datenschutz.vue, pages/impressum.vue, pages/mensa.vue, pages/plan/_timetable.vue
Es läuft eigentlich so wie ich es will, jedoch nur wenn ich die Seite über eine URL lade. Wenn ich dann auf der Seite bin und auf eine andere Page z.B. Mensa gehe, werden die Metatags für die Description einfach gelöscht und nicht ersetzt.
Hast du eine Idee?
https://nuxtjs.org/api/pages-head
müsste eigentlich so funktionieren
=> Improve Meta Tags

server/controllers/news.ts
Zeitstempel in den Cache-Key zu schreiben macht keinen Sinn für Daten, die sich nicht täglich ändern
=> News API: Remove timestamp from cache keys

server/controllers/news.ts
Das News-Widget auf der Ostfalia-Seite schickt einen Request mit einigen Query-Parametern.
In der News-API wird eine vereinfachte Version abgespielt und das Ergebnis geparst.
Einen zusätzlichen Parameter `showDate` habe ich angeschaltet und damit hat die Ostfalia-News-API jetzt auch Zeitstempel.
=> News API: Get more Ostfalia news and add dates

store/news.js
"Dr. Max Muster gewinnt Preisausschreiben" wird fälschlicherweise zu "Dr.", also wird nach dem letzten Satz bei mehr als 50 Zeichen Textlänge erst abgeschnitten.
=> Campus News: Truncate only after 50 chars

nuxt.config.js, package-lock.json
Motivation:
* Mit vuetify-loader wird kein vuetify-CSS eingebunden, was nicht genutzt wird (siehe https://vuetifyjs.com/en/framework/a-la-carte#vuetify-loader). Das reduziert die Größe der CSS-Datei.
* extractCSS zieht das CSS aus der index.html in eine seperate Datei. Das führt dazu, dass CSS und JavaScript gleichzeitig geparsed werden können und das erste Rendering schneller ist. Das macht Sinn, wenn man viel CSS hat.
* Die dadurch aktivierte Abhängigkeit PostCSS in der Build-Kette scheint das parallele Bauen nicht zu unterstützen und wirft einen kryptischen Fehler.
* postcss wurde nicht geladen. Nach einer Installation und anschließender Deinstallation des Pakets ging es wieder, vorsichtshalber habe ich die aktualisierte package-lock mit committed.
=> Use vuetify-loader

model/RichLecture.spec.ts, model/RichLecture.ts, package-lock.json
'IE-Wissensmanagement' und 'ITM-Wirtschaftsrecht' werden die gleichen IDs zugeteilt, was Probleme verursacht. Um das Problem kurzfristig & rückwärtskompatibel zu lösen, habe ich eine Ausnahme hinzugefügt.
=> Hotfix title id collision

assets/meta-information.json, nuxt.config.js, pages/datenschutz.vue, pages/impressum.vue, pages/index.vue, pages/mensa.vue, pages/plan/_timetable.vue, store/splus.js
* Wie vorgeschlagen in #226, ersetze einzeln gesetzte Descriptions durch ein globales Template
* Setze den Dokumententitel für nicht personalisierte Pläne
* Benutze eine längere Beschreibung, um weniger Abkürzungen im Titel stehen zu haben - in umgekehrter Reihenfolge, um die wichtigste Information vorne stehen zu haben
Die description-Tags verschwinden immer noch bei einem Seitenwechsel.
=> Use meta description template

plugins/vue-matomo.js
`app.$router` gibt es nicht, also werden nach dem initial pageview keine pageviews getrackt 😮
=> Fix Matomo not tracking pageviews

components/general-timetables-list.vue
Reduziere die Anzahl HTML-Elemente von 6300 auf 5000 (20%) durch das Entfernen von nicht notwendiger Elemente in der general-timetables-list. Verbessert die Performance ein wenig.
=> General timetables list: Reduce # of DOM nodes

components/dayspan-custom-event-popover.vue, components/spluseins-calendar.vue
* Rendere das custom event popover nur auf dem Server (ssr-only) - dadurch wird das HTML nur angezeigt und die Vue-Komponenten werden nicht initialisiert
* Entferne nicht genutzten Code aus dem popover
Dadurch verbessert sich die Rendering-Performance für einen gefüllten Kalender von (edit) 730ms auf 500ms.
=> Lazy load event popover

server/lib/SplusApi.ts
Bei parallelen Anfragen an splus wird nur eine Anfrage beantwortet.
Durch das Setzen einer zufälligen SessionID soll das umgangen werden.
Der Bug ist nur schwer reproduzierbar, deswegen konnte ich den Code auf den Fall nicht testen.
=> Create random splus session to prevent collisions

pages/index.vue
Mit den `order-xs1`-Attributen kann man die Reihenfolge der Elemente auf verschiedenen breakpoints definieren (https://vuetifyjs.com/en/framework/grid#unique-layouts).
Für die faculty-news-card funktioniert das nicht, weil sie verschachtelt ist.
Verbessert die Performance nur um 30ms auf meinem Laptop.
=> Render dashboard only once

store/splus.js
Führt dazu, dass nur die verwendeten Funktionen im bundle enthalten sind. Reduziert unser Frontend-Javascript um 11.5kb (gzip-komprimiert) (4%).
=> Reduce build size importing only chroma.scale

plugins/vuetify.js
Reduziert die Build-Größe um 90kb (gzip-komprimiert) (20%).
Wir haben versehentlich alle vuetify-Komponenten zwei mal importiert. Die Zeile im a la carte - Guide (https://vuetifyjs.com/en/framework/a-la-carte#vuetify-loader) habe ich übersehen.
=> Use vuetify-loader correctly

nuxt.config.js
Reduziert die Größe der JavaScript-Dateien von 466kb auf 370kb (gzip-komprimiert) (20%)
Wir importieren moment js und dayspan auch. Ich habe nicht herausfinden können, warum deswegen die Bibliothek zwei mal eingebunden wird - an der Version liegt es nicht. Durch Deduplizierung könnte man noch einmal 17kb (gzip-komprimiert) sparen.
=> Remove unused moment js locales

components/responsive-icon-button.vue, plugins/vuetify.js
Siehe https://vuetifyjs.com/en/framework/a-la-carte#functional-components, die imports können nicht automatisch festgestellt werden, wenn man functional components verwendet werden.
=> Fix responsive icon buttons missing imports

components/course-multiselect.vue
Schreibe alle Informationen in eine Spalte, um die Tabellenbreite auf xs zu reduzieren.
Auf iPhones sollte man die Tabelle jetzt normal scrollen können.
=> Course multiselect: Reduce table width on xs

components/course-multiselect.vue
Wenn ich auf meinem Smartphone die Liste der Kurse scrolle, kann ich nicht immer sehen, welche Kurse sich konkret überlappen.
Ich habe die Checkbox für Kurse mit Konflikt gelb gefärbt. Ist das intuitiv? Ich denke, dass sich die Bedeutung aus dem Kontext mit der gleichfarbigen Warnung ergibt und durch die Änderung der Farbe bei der Auswahl.
Alternativ könnte ich auch ein Icon anzeigen.
=> Course multiselect: Highlight conflicts

middleware/cached.js
Der Netlify-Build wirft einen Fehler (und macht nach ein paar Minuten trotzdem weiter), weil bei `nuxt generate` Middlewares keinen Zugriff auf `res` haben. Es können dann keine Cache-Header gesetzt werden.
=> Cache middleware: Skip during static build

package-lock.json, package.json, server/lib/v2/SplusParser.ts
Die ICS werden über die "neue" Api generiert, beim parsen der Events aus splus.ostfalia wird nun immer die Berliner Zeitzone genommen. Man kann da nicht mit utcOffsets arbeiten, weil diese sich durch die Zeitumstellung verändern. Den Kalender betrifft das nicht, weil dieser noch mit der "alten" Api läuft.
Das Problem ist erstmal gelöst aber beim Umbau des Frontends auf die "neue" Api müssen wir dann darauf achten, dieses enstprechend anzupassen.
=> Use moment timezone Europe Berlin

nuxt.config.js
Wir müssen nicht das ganze CSS importieren, sondern `vuetify-loader` sorgt dafür, dass nur das CSS für die tatsächlich verwendeten Komponenten geladen wird.
Steht so in der Dokumentation, habe ich in #269 überlesen.
Edit: In der Netlify-Preview sind es 60kb weniger im Vergleich zu master
=> Use vuetify a la carte css

pages/index.vue, pages/mensa.vue, pages/plan/_timetable.vue, store/index.js
nuxtServerInit ist eine action in `store/index`, die (nur) serverseitig einmalig ausgeführt wird. Weil die action vor den middlewares ausgeführt wird, werden auftretende Fehlermeldungen erkannt und im Fehlerfall keine Cache-Header gesetzt.
Probleme / Nachteile: In der Implementierung dieses PRs werden die Mensa- und Newsdaten immer und die Plandaten nie in server init geladen. Heißt:
* bei einem direkten Seitenaufruf eines Plans werden unnötig Daten geladen
* tritt ein Fehler nur bei der splus-API auf und nicht bei den anderen, wird trotzdem der cache header für diese Planseite gesetzt
Weil die meisten Nutzer aber über das Dashboard kommen und die API nur Totalausfall hat, halte ich das erst einmal für annehmbar.
Dokumentation: https://nuxtjs.org/guide/vuex-store#the-nuxtserverinit-action …
=> Use nuxtServerInit to load data from API

components/spluseins-calendar.vue, store/splus.js
Vereinfache den splus-Store durch das Entfernen des lecture-Cachings und durch Extrahieren von timetable und upcoming timetable gemeinsamer Logik.
=> Remove lecture caching from splus store

components/dayspan-custom-calendar.vue, components/spluseins-calendar.vue
Vorher:
* dayspan-custom-calendar ändert die Woche
* spluseins-calendar watcht die Woche, lädt und aktualisiert die Events
* dayspan-custom-calendar aktualisiert die Events
Das Problem ist, dass der Kalender für kurze Zeit leer ist. So flackert er.
Mit diesen Änderungen:
* dayspan-custom-calendar feuert die Events today/next/prev
* spluseins-calendar hört auf das Event, lädt die Daten, aktualisiert die Events und wechselt dann die Kalender-Ansicht
=> Calendar: Block week change until lectures are loaded

store/splus.js
Das direkte Laden einer Seite wirft keinen TypeError mehr.
Siehe https://github.com/nuxt/nuxt.js/issues/3579#issuecomment-411240994
=> Don't store moments, fixes SSR induced type error

pages/plan/_timetable.vue
WatchQuery funktioniert zwar, man muss aber noch angeben was neugeladen werden soll.
=> Fix switching between custom timetables

static/.well-known/assetlinks.json
Als Teil von #333, siehe https://developers.google.com/web/updates/2019/02/using-twa
=> Add assetlinks.json for TWA

components/dayspan-custom-event-popover.vue
Die Beschreibung wird zu lang, deswegen overflow-y
=> Calendar: Add scroll bar for long descriptions

components/dayspan-custom-event-popover.vue
Was bisher passiert (happy path):
* Der Nutzer lädt die Startseite, diese wird auf dem Server gerendert
* Der Nutzer lädt einen Plan, dieser wird auf dem Client gerendert, der @close-Handler wird deswegen attached
Was bisher passiert (Fehlerfall):
* Der Nutzer lädt einen Plan direkt, dieser wird auf dem Server gerendert
* Der Client lädt Vue für diese Komponente nicht (`ssr-only`, das verbessert die Performanz). Kein @close-Handler wird attached! Die Karte lässt sich nicht schließen.
=> Custom event popover: Enable hydration, fixes inactive close button

server/webpack.config.js
`fetch` wird nicht korrekt gepolyifillt, siehe https://github.com/bitinn/node-fetch/issues/450#issuecomment-494475397
=> Bus API: Hotfix missing reference to fetch in production build

web/nuxt.config.js
Die meisten Suchanfragen gehen an "splus ostfalia" + (optional) Fakultät, wenn das in der description auftaucht, ranken wir für das Keyword vielleicht etwas höher.
=> Add 'splus' to description

web/pages/index.vue
Die Beschreibung für Suchmaschinen für die Homepage war bisher "Startseite", mit dieser Änderung wird es die in nuxt.config.js geschriebene
=> Use default description for index page

README.md, server/controllers/splus.ts
`SKED_IP_WHITELIST_PREFIX=''`, damit man den Server lokal testen kann, ohne in der Ostfalia zu sein
=> Expose whitelisted IPs as env var

web/components/spluseins-calendar.vue, web/plugins/vuex-persist.js
alte IDs aus den Browser-Stores löschen
=> Reset schedules stored in browser

web/components/spluseins-cookie-snackbar.vue, web/plugins/vue-matomo.js
Wenn ich AdBlock an habe, lädt das Matomo-Skript nicht und beim Interagieren mit dem Cookie-Popup bekomme ich Serverfehler :(
Gefixt mit zwei ifs
=> Fix TypeError when matomo is blocked

server/lib/SplusApi.ts
Für alle Wochen wird die gleiche sked-URL abgerufen, deswegen ist es sinnvoller, pro Plan nur einen Cache zu haben statt 1 * Anzahl Wochen Caches.
=> Cache sked timetables by id, not by id+week

README.md, web/nuxt.config.js, web/pages/datenschutz.vue, web/pages/impressum.vue
In der nuxt config wird beim build `PROTECTED_INFORMATION` aus den Umgebungsvariablen geladen und daraus das Team als `process.env.team` in die Komponenten geschrieben.
https://nuxtjs.org/api/configuration-env/
…das macht das Deployment einfacher
=> Allow injection of team members via env variable

web/components/support-us-card.vue
Different chars were used for the dash 
This char is now used: –
This char was replaced: -
=> Equalize dashes

server/assets/timetables.json, web/assets/timetables.json
Hi,
wie angekündigt gibt's hier einmal die neuen URLs der Fakultät E.
Im Vergleich zum letzten Semester haben sich einmal die URLs vom Format deutlich geändert, außerdem gibt's die seperaten Matheplus-Dinger im ersten Semester nicht mehr.
Ich hab einmal alle per API only auf Availability getestet und sah gut aus. Ich hab aber die UI lokal noch nicht ans laufen bekommen, sodass vielleicht trotzdem noch obvious Fehler drin sein könnten.
URLs habe ich von https://www.ostfalia.de/cms/de/e/studium/stundenplaene/
=> Add faculty E timetables

server/lib/NewsApi.ts
Faculty E switched to the same news "system" as faculty R, but they host it on a different subpage, see https://www.ostfalia.de/cms/de/e/studium
Fixed that and faculty news now successfully show for me (through the API)
=> Fix faculty E news

server/lib/NewsApi.ts
Einen hab ich noch, da die Fakultät E-News gerade etwas buggy angezeigt werden:
* When a link was in the description, its text was appended to the title. Now it's using only the first link.
* When the description contained an empty paragraph at the end it was displayed as empty. Now it selects all paragraphs but the first that are not empty
=> Fix faculty news parsing

web/components/support-us-card.vue
+ bitcoin und mail entfernt weil sie noch nie verwendet worden sind
=> Add new supporters

server/controllers/ics.ts
Previously it made requests to https://stundenplan.ostfalia.de/undefined, which ofc returns 404
Soweit ich sehe war das einfach nur ein Bug wegen fehlendem Attribut, aber evtll hab ich die Logik da auch fehl verstanden?
=> Fix ICS when no cache for that timetable is available

web/components/custom-timetable-dialog.vue
use current or selected week instead of hardcoded semester start for loading all lectures
#449
=> Workaround for #449 (personalised plans not working)

web/components/spluseins-calendar.vue, web/store/splus.js
Fixes #453. Damit kann man auch nach Ende des Jahres noch in's letzte Jahr/Wintersemester zurückgehen und vergangene Termine anschauen. Außerdem vereinheitlicht das etwas den Kalender-Code.
Im Prinzip ändert sich an der Logik nichts mit Ausnahme, dass ich `this.refresh()` und `this.calendar.next()` getauscht habe.  Damit das aber dann wegen dem Refresh nicht flickert, übergebe ich `next()` und `prev()` true als Parameter, damit er nicht automatisch refresht. 
Der Calender wird dann in der `refresh()`-Funktion manuell erneuert.
=> Fix year wraparound at end of wintersemester

docs/server.md, server/controllers/ics.ts, server/controllers/splus.ts, server/lib/SkedParser.ts, server/lib/SplusApi.ts, web/components/custom-timetable-dialog.vue, web/store/splus.js
* New endpoint for loading unique lectures metadata for a single timetable, fixes #449. Also has the advantage that past semester events are still available for selection in the dialog. 
* Improve caching: Store the parsed events instead of storing only the raw response. Improves responsiveness **after** first load by a lot. First load (without cache) stays approximately equal (or a few milliseconds slower).
Timing measurements in backend (Handel und Logistik 1. Semester PO 2018, 193 lectures total):
|    |      Old version      |  New version |
|----------|-------------|------|
| average (5 runs) of first load without cache | 620 ms |  650 ms |
| average (5 runs) of loads with cache |    380 ms   |   10 ms |
This makes switching between weeks more responsive than before.
=> Implement unique lecture fetch in backend and improve backend caching

docs/semesterbeginn.md, docs/server.md, server/assets/timetables.json, server/controllers/ics.ts, server/controllers/splus.ts, server/lib/SkedParser.ts, server/lib/SplusApi.ts, server/model/SplusEinsModel.ts, server/package-lock.json, server/package.json, web/assets/timetables.json
Neue Informatik-Pläne mit CSV!
Änderungen:
* `csv-string` library für's CSV-Parsen hinzugefügt
* Den `graphical`-Parameter in der `timetables.json` umbenannt in `type`, akzeptiert entweder `list`, `graphical` oder `csv`.
* Die bestehenden Timetables auf das neue Format konvertiert mittels https://github.com/SplusEins/sked_parser/commit/7a0d5a2db2e04220ac9569ee648f9a341d55fd8e. Dabei wurden auch direkt neue Timetables der Versorgungstechnik hinzugefügt. Der `timetables.json`-File ist jetzt zudem sortiert, sodass Änderungen in Zukunft leichter vergleichbar sind. 
* Docs aktualisiert auf neues Format.
=> New informatik timetables with CSV

docs/server.md, server/controllers/news.ts, server/lib/NewsApi.ts, server/package-lock.json, server/package.json, web/components/campus-news-card.vue, web/components/faculty-news-card.vue, web/store/news.js
Teil 1 für #456. Die Dashboard-Änderungen werden in einem zukünftigen PR kommen, der hier ist quasi backend-only.
* Alle Ostfalia-News werden (wie vorher nur die Campus-News) über den speziellen Ostfalia-Endpoint bezogen. Dadurch werden jetzt fast alle Fakultäten supportet und es gibt insgesamt weniger Wartungsaufwand.
* Der API-Endpoint erwartet jetzt eine Liste von News-Typen, die geladen werden sollen. Dadurch werden zB die API-Responses für die Startseite deutlich verkleinert, da nur die notwendigen News geladen werden.
* RSS-Feed-Support mittels angehängtem `.rss` im API-Call.
* Kürzen der News wurde verbessert
Supported: `r`, `b`, `k`, `h`, `f`, `g`, `w`, `e`, `s`, `wob`, `wf`, `sud`, `sz`, `campus`, `campus38`. Informatik (und einige andere) sind nicht dabei, da die Fakultäten ein …
=> API: Improve news fetching/parsing and add RSS support

server/lib/SplusApi.ts
Durch den neuen unique lecture endpoint (#455) wurde ein kritischer Bug hinzugefügt, bei dem ich die Start- und End-Daten einiger Events im Cache genullt habe. 
Das Nullen an sich ist zwar beabsichtigt, aber die Kombination aus der Caching-Logik und mein Unwissen über javascripts pass by reference für diese gecachten Event-Objekte hat dafür gesorgt, dass der Cache corrupted wird. 
Konkret wurden die Events der ersten Woche nicht mehr alle angezeigt, sobald man einmal einen personalisierten Plan erstellt hat. Das hält so lange an, bis der Cache erneuert wird. Als Workaround hab ich die Cache-Dauer temporär auf 15 Minuten reduziert, aber das hier sollte trotzdem so schnell wie möglich gemergt werden.
Gefixt habe ich das hier, indem das Array mittels slice() zuerst kopiert wird und danach …
=> Fix a critical bug where the start and end date of cached events were corrupted

.github/workflows/timetables.yml
Die Github Action läuft einmal pro Tag und führt den sked-parser aus. Anschließend wird ein PR geöffnet, damit die Changes reviewed werden können. Sollte noch ein PR offen sein, wird stattdessen der existierende PR bei Änderungen force gepusht. Siehe auch https://github.com/l3d00m/SplusEins/pull/3
Vorteile:
* Wir kriegen direkt mit, wenn sich URLs der Pläne verändern
* Mehr Automatisierung 🥳
Nachteile:
* Wenn der PR offen ist und man noch manuell nacharbeitet (weil irgendein Label oder so nicht stimmt, passiert gelegentlich mal), wird der PR nach dem Merge neu geöffnet, da dann ja Changes vorhanden sind. Das kann man IMO nicht wirklich verbessern, außer dass man halt einfach den Workflow deaktiviert, sollte das zu sehr stören.
Idee aus #464 ♥️
=> Automatically update timetables (daily) with sked-parser and github actions

web/components/upcoming-lectures-card.vue
* Nächste Vorlesung auf dem Dashboard wird jede Minute mittels setInterval erneuert (ähnlich wie beim Bus-Plan)
* Vorlesung wird auch 15 Minuten nach Start angezeigt (wenn man zu spät kommt :D)
* Bisschen refactored, damit vue `computed` statt `watch` genutzt wird
Gleich live auf https://staging.spluseins.de/
=> Refresh next lecture on dashboard automatically and keep showing it for a few minutes after start

server/controllers/mensa.ts, server/package-lock.json, server/package.json, web/pages/bus.vue, web/pages/index.vue, web/pages/mensa.vue, web/store/index.js
SplusEins is currently down/times out since today because OpenMensa is down (to be precise, OpenMensa is still accepting requests, but all requests are timing out).
This leads to the following situation: The server side OpenMensa request had no timeout configured, so it ran unitl the OS limit (usually 2-5 minutes until it was reached). 
SplusEins SSR depended on the API for the first load because it calls `mensa/load` in `nuxtServerInit` of`store/index.js`.
Fixes:
* server side timeout of 3 seconds for all OpenMensa requests
* Load mensa (and bus for any future issues) on client side only, do not block for it
=> Fix SplusEins down/timeout because OpenMensa is currently down

docs/deployment.md, docs/konfiguration.md, web/.vscode/launch.json, web/nuxt.config.js, web/package-lock.json, web/package.json
Neues Deployment mit dem nuxt-Proxy Modul, anstatt das selber mit nginx zu konfigurieren. Ist bereits online und läuft, der PR hier ist nur noch zu Doku-Zwecken.
Vorteil: Das Deployment ist deutlich leichter und man kann mehr die nativen Dokku-Features nutzen und hat nicht mehr diesen etwas merkwürdigen doppelten Nginx Reverse Proxy, wie wir es vorher hatten.
Außerdem vermeiden wir damit CORS-Probleme, die wir vorher hatten, da beim Aufruf von spluseins.de die API unter spluseins-i.ostfalia.de/api aufgerufen wurde.
=> Use nuxt as proxy for API and docs instead of manually configured nginx

server/controllers/mensa.ts, server/webpack.config.js, web/pages/index.vue
timeouts are now working properly if openmensa should be down again, also we are sending some more helpful status codes
=> Catch OpenMensa timeouts properly and display better mensa errors

server/controllers/splus.ts, server/lib/SplusApi.ts, web/layouts/error.vue, web/pages/plan/_timetable.vue, web/store/bus.js, web/store/mensa.js, web/store/news.js, web/store/splus.js
* Detect sked errors and return appropriate status codes instead of 500 Internal Server Error (i.e. if a timetable is no longer available, just return 404)
* Error Snackbars in UI now have "simpler" texts, they display a simple error and the error status code
* 404 errors for timetables are now properly raised (so the nuxt error page is shown) and it says "plan nicht gefunden" instead of "diese seite gibt es leider nicht..."
live on https://staging.spluseins.de in short
=> Improve error detection and handling throughout SplusEins

web/pages/bus.vue, web/store/bus.js
make cards smaller to fit content and show skeleton loaders when still loading (noticable on slower connections)
=> Improve bus layout, use skeleton loaders

web/components/faculty-news-card.vue, web/components/spluseins-calendar.vue, web/pages/bus.vue, web/pages/mensa.vue, web/plugins/pwa-update.js, web/store/news.js
* vuex-persist is too slow, which is why the faculty news always showed "wolfenbüttel", this is fixed by implementing a watcher (bug added with #463)
* hide old bus departures (because it looks bad if all departures are a few days ago when there's no network)
* always refresh timetable to avoid outdated stuff in PWA
=> Fix wrongly shown faculty news and always refresh bus + timetables

server/model/SplusEinsModel.ts
If you set the CENSOR_DISABLE environment variable to true, the lecturer name won't be censored anymore. The default is to censor.
This can be useful if you want to host a private instance of SplusEins that is not publicly available.
=> Added option to disable censoring of names

server/controllers/bus.ts, server/package-lock.json, server/package.json, web/components/basic-utilities-list.vue, web/components/spluseins-side-nav.vue, web/pages/bus.vue, web/store/bus.js
Since HAFAS was deactivated, the bus schedule component has no longer been functional. I replaced the outdated hafas-client library with the drop-in library [motis-fptf-client](https://github.com/motis-project/motis-fptf-client) to restore functionality.
I asked for permission to use it in their [Matrix channel](https://matrix.to/#/%23transitous:matrix.spline.de), which was granted. In addition, I increased the width of the bus card columns to avoid unnecessary line breaks when “(in a few seconds)” was appended. I also added a “Last updated” property to the component to provide more transparency when an update has occurred.
Should close #949. Commits can be squashed if you guys want, since I fucked up a bit - whoops.
TLDR:
- replaced hafas-client library with motis-fptf-client
- updated …
=> Hafas motis fptf client swap
