SplusEins/SplusEins

- assets/courses.json
- components/spluseins-calendar.vue
Bitte einmal grob durchklicken und schauen, ob ich etwas falsch copy pasted habe :)
Ich weiß nicht, was Soziale Arbeit: "S-BP" ist, hat jemand eine Idee?
Edit: Der Farben-Generierungs-Algorithmus hat für manche lectures "schwarz" ausgespuckt, was nicht die Variante "light1" besitzt. Das hat zu einem scheinbar zufälligen "invalid property 1"-Fehler geführt. Ist jetzt gefixt.
> Add more courses

- components/dayspan-custom-calendar.vue
Der Header des Kalenders sieht nun schöner aus, hängt nun nicht mehr in die Mitte und der "Heute" Button verschiebt nun nicht mehr die Wochenansicht.
> Calendar header

- components/custom-timetables-list.vue
- components/favorite-timetables-list.vue
- components/general-timetables-list.vue
- components/spluseins-side-nav.vue
- store/courses.js
Wie von @hidotp vorgeschlagen ohne Icons
> Reduce sidenav list depth by 1

- components/dayspan-custom-calendar.vue
- components/spluseins-header.vue
- components/spluseins-side-nav.vue
- auf mobilen Geräten muss man nun nicht doppelt klicken um das side-nav zu öffnen
- auf mobilen Geräten wird nun ein kürzeres Datum angezeigt (keine ausgeschriebenen Monatsnamen)
- auf mobilen Geräten wird statt dem Heute-Button ein Icon-Button angezeigt
> Responsiveness improved

- components/dayspan-custom-calendar.vue
- components/spluseins-calendar.vue
- store/schedule.js
- wenn Samstags Veranstaltungen sind wird der Samstag angezeigt (Bsp. Soziale Arbeit Bachelor 2.Sem)
- sonst wird nur Montag-Freitag angezeigt
> Display only weekdays with lectures

- store/splus.js
> Fix wrong week being fetched on Sundays

- components/dayspan-custom-calendar.vue
> Calendar: Visibly highlight current day in dark mode

- components/dayspan-custom-calendar.vue
- components/general-timetables-list.vue
- layouts/default.vue
- pages/index.vue
- store/splus.js
Änderungen:
* Statt standardmäßig 1. Semester Informatik zu laden, wird eine leere Seite angezeigt. Dort kann das Logo hin (inspiriert von VS Code).
---
Edit
_Mehr Änderungen sind erst einmal nur im branch feature/dynamic-schedule-route, weil ich mit dem Ergebnis noch nicht zufrieden bin:_ #39
> Landing page

- .babelrc
- __mocks__/file-mock.js
- __mocks__/style-mock.js
- components/__tests__/spluseins-about.spec.ts
- components/spluseins-about.vue
- jest.config.js
- package.json
- shims-tsx.d.ts
- shims-vue.d.ts
Hier liegen über 8 Stunden Debugging begraben.
> Setup frontend tests

- components/spluseins-side-nav.vue
> Close drawer after schedule selection

- store/splus.js
Das übliche. Keine Ahnung, so geht's
> Fix empty schedule on Sundays

- concourse/build-frontend.sh
- concourse/build-frontend.yml
- concourse/credentials.yml.example
- concourse/pipeline.yml
- process-dev.yml
- process-prod.yml
In der Pipeline kann nun manuell der Deploy auf spluseins.de gestartet werden.
> CI - Automate deploy on Prod.-Environment

- concourse/pipeline.yml
- concourse/tests.sh
- concourse/tests.yml
- process-dev.yml
- process-prod.yml
- server/model/RichLecture.spec.ts
Tests werden nun beim Dev-Build ausgeführt.
Tests beim Prod-Build sind nicht nötig, da der Prod-Build erst ausgeführt werden kann, wenn der Dev-Build grün ist.
> CI - Tests automation

- plugins/dayspan.config.js
- store/splus.js
Farben: light-blue darken 4 & cyan darken 4
Außerdem: blend-Faktor in dayspan.config.js angepasst
> Adjusting Schedule Colors

- assets/schedules.json
- components/favorite-timetable-dialog.vue
- components/favorite-timetables-list.vue
- components/timetable-select.vue
- plugins/vuex-persist.js
- store/splus.js
- man kann jetzt Favoriten hinzufügen und wieder löschen
- die Favoriten werden im Browser gecached
- bei der UI habe ich mich an der von "Eigne Stundenläne" orientiert und Code wiederbenutzt
TODO:
> Favorite schedule

- components/home-button-list.vue
- components/spluseins-header.vue
- components/spluseins-side-nav.vue
* "Startseite"n-Eintrag hinzugefügt
* Klicken auf den Titel leitet auf die Startseite weiter
Motivation: Die Startseite soll Platz für News-Inhalte bieten und mehr
> Add button for home page

- components/custom-timetables-list.vue
- components/timetable-select.vue
hydration-Probleme, Details unbekannt
> Fix console warnings

- components/course-multiselect.vue
- components/custom-timetable-dialog.vue
- components/timetable-select.vue
> Fix timetable select not reacting, sort courses in course multiselect, improve wording

- components/custom-timetable-dialog.vue
- pages/_schedule.vue
- store/splus.js
nach #68 ging der Seitenwechsel nicht mehr, weil die gecachten Daten nicht gelöscht worden sind
> Fix no schedules loading after route change

- components/course-multiselect.vue
featuring some cryptic JavaScript
Beim Design ist mir nichts besseres eingefallen
> Custom schedule: Warn when courses overlap

- server/controllers/splus.ts
Wenn ein Verbindungsfehler zwischen dem API-Server und splus auftritt, gibt die API jetzt einen Fehler 500 zurück und der Client muss nicht auf einen request timeout warten.
Durch die Fehlerbehandlung im Frontend wird die Fehler-Snackbar angezeigt, wenn die API einen Fehler erzeugt.
> API: Handle connection errors

- components/__tests__/spluseins-about.spec.ts
- components/__tests__/spluseins-impressum.spec.ts
> Mock matomo in tests

- components/custom-timetable-dialog.vue
https://trello.com/c/C6Au8Nd0/226-anzahl-basis-pläne-und-anzahl-kurse-beim-speichern-eines-eigenen-pläns-tracken#
> Additional Matomo tracking 

- components/custom-timetables-list.vue
@schneefux guter Tipp mit der "exact" Property
https://vuetifyjs.com/en/components/jumbotrons#api
> Fix highlighting of custom timetable list items

- components/spluseins-calendar.vue
- store/splus.ts
monent().day() ist für Sonntag 0 und für Samstag 6
> Fix week-change of timetable on sundays

- assets/timetables.json
Änderungen:
* Setpläne der Fakultät Maschinenbau nach bestem Wissen eingetragen.
Probleme, die aufgetreten sind:
* BMec7 wird in splus im Set BMecW1 genannt, hat also zwei Namen (evtl. ist nur einer richtig?) ich habe die erste Bezeichnung gewählt
* MSE2 ist auf splus falsch im ersten Semester eingetragen
> Timetables: Add Maschinenbau

- server/lib/SplusApi.ts
- store/splus.ts
> API: Request 'Sommersemester' from splus

- components/spluseins-calendar.vue
Zusammen mit #161 und #165 sollte Informatik auf SS19 umgestellt sein.
> Fix week transition in 2019

- assets/timetables.json
Müssten jetzt alle Pläne aus splus eingebunden bzw. aktualisiert sein.
> Add Karl Scharfenberg + Versorgungstechnik + Update other IDs

- server/controllers/news.ts
- server/controllers/splus.ts
Added `/api/news/ostfalia/e` (Elektrotechnik), `/api/news/ostfalia/i` (Informatik) und `/api/news/ostfalia/r` (Recht)
> Add Ostfalia faculty news

- components/custom-timetable-cookie-reminder.vue
- components/custom-timetable-dialog.vue
- components/spluseins-cookie-snackbar.vue
> Reminder dialog for cookies

- components/general-news-card.vue
- components/specific-news-card.vue
- store/news.ts
Werden News geladen, so wird dies über das Icon signalisiert.
> Signalize loading of news

- components/dayspan-custom-calendar.vue
- store/splus.ts
Beim aufräumen der Custom-Dayspan-Calendar Komponente sind mir ein paar Bugs aufgefallen, die ich gleich noch behoben habe.
1. Bug:
Um das Problem zu lösen habe ich die summary-Funktion umgeschrieben und moment benutzt.
2. Bug:
Ab dem 31.März waren, vermutlich durch die Zeitumstellung, alle Events um 1 Stunde verschoben.
> Fix calendar bugs && Cleanup of custom-dayspan-calendar-component

- server/controllers/news.ts
Die alte News-Seite war besser…
> News API: Update faculty i parser

- components/timetable-select.vue
Bricht jetzt auf iPhone 5 um, kann man nix machen
> Custom Timetable dialog: Replace load button icon by text

- components/spluseins-header.vue
- components/spluseins-side-nav.vue
- store/ui.ts
> Open navigation drawer by default on desktop

- concourse/build-frontend.sh
- concourse/build-frontend.yml
- concourse/insert-information.sh
- concourse/insert-information.yml
- concourse/pipeline.yml
- concourse/tests.yml
Das Einfügen der Namen geschieht nun vor dem Bauen des Frontends 😅
> Fix Concourse

- components/basic-utilities-list.vue
- components/custom-timetable-dialog.vue
- components/custom-timetables-list.vue
- components/dayspan-custom-calendar.vue
- components/favorite-timetables-list.vue
- components/general-timetables-list.vue
- components/spluseins-about.vue
- components/spluseins-calendar.vue
- components/spluseins-header.vue
- layouts/error.vue
- plugins/vue-matomo.js
Auf der Suche nach dem Ursprung von "event name not defined" habe ich den Whitespace angepasst und `trackMatomoEvent` durch eine global injizierte Funktion ersetzt.
> Matomo code cleanup

- assets/timetables.json
Maschinenbau 1. Semester BM1 Plus konnte nicht geladen werden.
> Fix not loading plan

- components/last-changes-card.vue
- components/spluseins-calendar.vue
Die Änderung der URL wurde als computed property nicht bemerkt. Außerdem habe ich den Change-Log gekürzt.
> Fix share Funktionalität + Change-Log kürzen

- package-lock.json
Lokal laufen die Tests, vielleicht löst sich das Problem durch eine geupdatete package-lock.json .
> Pipeline Tests

- components/calendar-action-bar.vue
- components/spluseins-calendar.vue
Nur die Trennung von Kalender und Buttonzeile aus #209
> Split calendar and calendar action bar

- assets/style/app.scss
- components/stats-card.vue
- components/upcoming-lectures-card.vue
- nuxt.config.js
- package-lock.json
- package.json
- pages/index.vue
- plugins/vue-css-donut-chart.js
- store/splus.ts
Auf der Startseite wird nun für den abbonierten Plan ein Kreisdiagram angezeigt.
> Add Stats Card

- server/controllers/news.ts
Wir könnten jetzt Campus 38 anschreiben, uns bedanken, ihnen mitteilen, dass wir nun ihren Feed benutzen und fragen ob sie einen Artikel über spluseins.de machen.
> Switch to campus 38 news feed

- concourse/pipeline.yml
- process-dev.yml
- process-prod.yml
> Ci restarts pm2 after deploy

- pages/index.vue
Zweiter Ansatz für #220 mit einem ähnlichen Ergebnis 🤔
> Reorder dashboard

- components/upcoming-lectures-card.vue
- pages/index.vue
Außerdem wird der Raum der Upcoming Lectures Card nur angezeigt, wenn er verfügbar ist (Studienstarttage Goslar).
> Display stats card only if there are any lectures

- components/basic-utilities-list.vue
- components/custom-timetable-dialog.vue
- components/general-timetables-list.vue
- components/select-dialog.vue
- components/spluseins-about.vue
- components/spluseins-footer.vue
- nuxt.config.js
- package-lock.json
- package.json
- plugins/lazy-hydrate.js
Reduziert die Rendering-Zeit des Dashboards von 1000ms auf 300ms (auf meinem Rechner im Entwicklungsmodus) 🎉 
Erklärung: https://markus.oberlehner.net/blog/how-to-drastically-reduce-estimated-input-latency-and-time-to-interactive-of-ssr-vue-applications/
Komponente: https://github.com/maoberlehner/vue-lazy-hydration
> Speed up rendering with lazy loading

- server/controllers/news.ts
- server/lib/SplusApi.ts
Zu splus wurde der Body nicht oder nicht richtig mitgeschickt, sodass immer nur der Plan für die aktuelle Woche geladen werden konnte.
> Fix fetch body params

- components/course-multiselect.vue
Vorher: Jeder gewählter Vorlesungsblock wurde mit jedem anderen gewählten verglichen (quadratische Zeitkomplexität)
Jetzt: Jeder gewählte Vorlesungsblock wird mit jedem anderen gewählten am gleichen Tag verglichen
Bei 6 Vorlesungen steigt die Performance von 500ms auf 50ms und die Auswahl fühlt sich wieder haptisch an.
> Course multiselect: Improve overlap detection performance

- components/upcoming-lectures-card.vue
> Typo: abbonieren -> abonnieren

- components/calendar-action-bar.vue
- components/open-calendar-dialog.vue
Wie von einem Nutzer vorgeschlagen, zeige einen Dialog, um die Möglichkeit zu geben, den Link in Google Calendar zu kopieren.
> Use a dialog for calendar subscription

- lib/chroma.js
- store/splus.js
Helferfunktionen haben gefehlt
> Fix chroma import

- components/calendar-action-bar.vue
- components/copy-text-dialog.vue
Vereinheitliche "Teilen" und "Extern öffnen"
> Copy text dialog: Use a bottom sheet

- components/dayspan-custom-calendar.vue
> Calendar: Center actions vertically on xs

- process-dev.yml
- process-prod.yml
Ein #281 oopsie, staging ist gerade down
> Fix wrong exec paths in pm2 API configs

- server/lib/v2/SplusApi.ts
Verhindere, dass die API leere Pläne zurückliefert, indem maximal eine Anfrage gleichzeitig an splus gestellt wird.
> API: Synchronize splus calls

- middleware/cached.js
- store/ui.js
Beißt sich das mit dem Caching?
> Add theme cookie

- components/spluseins-calendar.vue
- store/splus.js
Keine funktionale Änderung, nur refactoring
> Use v2 events for calendar events

- package-lock.json
- package.json
Siehe #294 und netlify/netlify-lambda#142
> Add encoding dependency to fix netlify function setup

- components/dayspan-custom-calendar.vue
- components/spluseins-calendar.vue
- store/splus.js
Wechsle ein paar Attribute von "lectures" zu "events"
> Refactor calendar

- components/calendar-action-bar.vue
- components/custom-timetable-dialog.vue
- components/custom-timetables-list.vue
- components/general-timetables-list.vue
- components/quick-access-card.vue
- components/timetable-select.vue
- lib/util.js
- pages/plan/_timetable.vue
- store/splus.js
`schedule` -> `timetable` für alle store-Getter
> splus store getters: Rename schedule to timetable

- server/controllers/splus.ts
- server/tsconfig.json
- store/splus.js
In Vorbereitung auf den Pull Request, der den Kurs-Select-Dialog überarbeitet
> splus API: Support fetching multiple weeks per call

- assets/timetables.json
War versehentlich identisch mit dem 2. Sem.
> Fix splus ID for Wirtschaftsinformatik 4. Sem.

- plugins/vuex-persist.js
Die Version wurde immer auf 2 gesetz und dadurch wurden immer alle Pläne gelöscht.
> Fix store version incrementing

- static/.well-known/assetlinks.json
> TWA: Fix space causing invalid assetlinks hash

- package-lock.json
- package.json
- server/controllers/mensa.ts
> API: Use self hosted XML API

- components/faculty-news-card.vue
- nuxt.config.js
- server/controllers/news.ts
- store/news.js
Remove unused Salzgitter, o̡͙̙̫͓̭̪h͖̲̳̜̻ n̷o̻̦̜ ̙̯͢n̥͍̦̜̻͔ͅo̢̞͉͚͇̘w̲̰̭̹̙̣̩ ̴̲̱̭͍̩͢w̷̫̥̠̪̣̤e̛̜͇͎̥͓͚̭ ̴͏̩͖̳̜͕r͎̤̹͟e̫̬̮͖͢m̴̫͔͡ó̹̳͔̺̻̜̭̟v̯̲͙̺e̢͕̲̙ḏ̴̭̤̪̤̝̜̺̟͡ ̶̥̗ͅs̴̢̝p̡̤͎͞a̤̙̜͞c̶̤̫è͚̟̭̺̳͟ą̧́̑̿̆͒̈̽ͣͫ̐͛̓͏̜͉̝̫͖̲͇̰̜͘͢n̨̥͇̞͓̪͓̝̞̖͇̣̻̮̊̽ͪ̈͛̽̏ͣͥͣͮ͛̚̕͝d̶̦̯̩̮̮̮͖̙̼̘̗̺̟̦͔̻̮̰̑̾̃͐͛̆̿̾͐ͨ͑͌́̽̇̕͘͝ ̵̢̢̗͓̤ͪ͐ͥ͊̑̅͑̎̋͟t́͐̌̽̓͐͐̐͂ͧͩ̚̚̕͏̳̦̪̞̬̪͉̼̖̬̝̙i̷͖͍̠̦̼̳̞ͬ̅̾ͯ̑̃ͨ͗͑̐̔̔ͧ̌͋̊̆͆̽͘͟ͅm̵̨̪̘̺̏ͮ͌ͧͬ̅ͩ̽̆͐̒ͩ̈ͨ̒̀̔ͪ̕e̶̜̬̯̻̬͉̖̦͑̑̈̇̊ͣ̾ͧͯͦ͌͗͠͠͝ ̴̵̤̮̳͖̊̄̇͑͟f̛̺̳̤̬̣̯͓̻̣̬̣͕ͬͩͩ̍̉̓̈̅̉͗ͯ̇̓̕ͅḁ̴̛͔͈̫̰̙͕͖͍̙̜̫͇͚̂̽̅̐̌͑̋̊b̡̧̛͓̠̖̘̞̻͕̙͌̇͒̾͊̎ͤ̀̚̚͞r̷̻̖͓̤̻̥͚̱͙͚̬̍̓ͩͫ͑͟͞i̶͔͍͔̥̤̰̯̯͇̤̻̍̂̀̑ͧ̍ͤͤ̕c̸͇̥̘͙̹͕̘̙̗̹̝̘̙̣͓̜͒ͣͯ̂̏̾ͫ̀͞͠
> Fix: Remove Salzgitter

- assets/timetables.ws.json
- components/general-timetables-list.vue
- components/timetable-select.vue
- server/controllers/splus.ts
- server/lib/SplusApi.ts
- server/model/SplusEinsModel.ts
- server/tests/Timetables.test.ts
> Add roomplan API and stubs for Informatik

- components/last-changes-card.vue
- components/support-us-card.vue
- pages/index.vue
> Add 'support us' card to index page

- web/nuxt.config.js
…damit wir die Statistiken der Google Search Console über Google-Suchen auswerten können
> Add google webmaster site verification

- web/components/stats-card.vue
- web/components/upcoming-lectures-card.vue
- web/pages/index.vue
- web/store/splus.js
> Refactor upcoming lectures: Use events instead

- server/assets/timetables.json
- server/controllers/ics.ts
- server/controllers/splus.ts
- server/lib/SkedParser.ts
- server/lib/SplusApi.ts
- server/model/SplusEinsModel.ts
- web/assets/timetables.json
> Faculty Recht

- server/assets/timetables.json
- server/lib/SkedParser.ts
- web/assets/timetables.json
> Feature bau wasser boden

- .gitignore
- server/assets/timetables.json
- server/lib/SkedParser.ts
- web/assets/timetables.json
> Add faculty G, K, F and S and sort json

- server/lib/SkedParser.ts
> Add another list parser

- web/components/custom-timetable-dialog.vue
ändere einen willkürlich gewählten Wert auf einen höheren Wert
> Increase max number of custom timetables to 8

- server/assets/timetables.json
- server/lib/SkedParser.ts
- web/assets/timetables.json
- web/components/general-timetables-list.vue
Der Raumplan hat wieder ein anderes Format, u. a. ein locale-Format für `datum` ("Dienstag, …")
> Add informatik-räume

- web/components/support-us-card.vue
…und entferne unsere Namen, weil die Liste zu lang wird
> Add supporter 'Uwe'

- server/assets/timetables-ss.json
- server/assets/timetables.json
- web/assets/timetables-ss.json
- web/assets/timetables.json
- web/plugins/vuex-persist.js
Beim Deployment daran denken, die Umgebungsvariable SEMESTER_WEEK_1 auf 41 zu setzten.
> WS20 Informatik

- web/components/support-us-card.vue
bin beim Zählen durcheinander gekommen
> web: Split florians in support us card

- web/package-lock.json
- web/package.json
Fix deploy after #444 
Da ich die Changes eh schon gemacht habe und getestet hab, mach ich auch direkt mal einen PR.
> Fix deploy by adding webpack and vuetify-loader as regular dependencies

- server/assets/timetables.json
- web/assets/timetables.json
Die CSVs wurden heute morgen nochmal geupdatet. Ich hab die direkt mal neu integriert, damit keine alten Pläne in SplusEins angezeigt werden.
> New Informatik timetables URLs

- server/lib/SplusApi.ts
- server/package-lock.json
- server/package.json
- web/components/course-multiselect.vue
- web/components/dayspan-custom-event-popover.vue
- web/components/upcoming-lectures-card.vue
Auf der Fakultät E werden die Räume teilweise direkt als Links angegeben. Das sieht aktuell schlecht aus, da direkt das HTML angezeigt wird.
Um diese Links darzustellen, werden die Räume jetzt direkt als `v-html` in Vue gerendert. Um Nebeneffekte (wie styles im html oder auch XSS) zu umgehen, sanitize ich das vorher im Backend.
Live auf https://staging.spluseins.de/
> Make room URLs clickable in UI

- server/assets/timetables.json
- server/lib/SkedParser.ts
- web/assets/timetables.json
- web/lib/util.js
- web/plugins/vuex-persist.js
- web/store/splus.js
* set semester start week
* increment storage version for vuex-persist
* manually add timetables from skedparser (only elektrotechnik, gesundheitswesen, soziale arbeit und handel faculty)
* fix a small bug that was introduced in #474 (jump to semester start was not working correctly)
live on https://staging.spluseins.de
> Updates for WS21

- server/controllers/mensa.ts
- server/model/SplusEinsModel.ts
- web/components/mensa-card.vue
- web/components/mensa-dayplan.vue
- web/pages/index.vue
- web/pages/mensa.vue
- web/store/mensa.js
* change API layout slightly 
* use typescript types more 
* display mensa loading bar
* don't use caroussel for mobile layout, it had a bug that the day sorting was random so we now just display the cards below each other
fixes #497
shortly live on https://staging.spluseins.de
> Use new mensa api

- server/assets/timetables.json
- web/assets/timetables.json
- web/lib/util.js
- web/package-lock.json
- web/plugins/vuex-persist.js
New plans and updates for next semester
> Changes for SS22

- web/components/custom-timetable-dialog.vue
- web/lib/util.js
> Fix saving custom schedules if nothing was changed

- README.md
- server/lib/SplusApi.ts
Dieser PR fügt den Räumen echte Addressen hinzu.  
Da würde ich feedback für haben wollen.
Primär für die ICS api, daher könnte die Funktion auch nach dort verschoben werden.
> Echte Adressen für die Räume

- server/controllers/bus.ts
- server/package-lock.json
- server/package.json
- web/components/basic-utilities-list.vue
- web/pages/bus.vue
- web/store/bus.js
Reverts SplusEins/SplusEins#1058
> Revert "Revert "Hafas motis fptf client swap""
